spring:
  application:
    name: ticket-service
  data:
    mongodb:
      uri: ${TICKET_MONGO_URI:mongodb://localhost:27017/ticketdb}
      auto-index-creation: true
server:
  port: ${TICKET_SERVICE_PORT:8083}
logging:
  level:
    root: INFO

