spring:
  application:
    name: seat-service
  data:
    mongodb:
      uri: ${SEAT_MONGO_URI:mongodb://localhost:27017/seatdb}
      auto-index-creation: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
server:
  port: ${SEAT_SERVICE_PORT:8081}
logging:
  level:
    root: INFO

