spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${PAYMENT_MONGO_URI:mongodb://localhost:27017/paymentdb}
      auto-index-creation: true
server:
  port: ${PAYMENT_SERVICE_PORT:8082}
logging:
  level:
    root: INFO

